### ISSUE TITLE
Cannot do 'make all'

### ISSUE THREAD

**Issue by JaeLee18** [HUJI-Deep/TMM#1]
Hello,
I already installed Caffe in my computer but I am getting an error.
When I do 'make all' in ~/TMM/deps/siments I got this:

PROTOC src/caffe/proto/caffe.proto
CXX .build_release/src/caffe/proto/caffe.pb.cc
CXX src/caffe/layers/absval_layer.cpp
In file included from ./include/caffe/layer.hpp:12:0,
                 from ./include/caffe/layers/absval_layer.hpp:7,
                 from src/caffe/layers/absval_layer.cpp:3:
./include/caffe/util/math_functions.hpp:140:1: error: ‘__forceinline__’ does not name a type
 __forceinline__ __device__ __host__ int8_t caffe_sign(Dtype val) {
 ^
./include/caffe/util/math_functions.hpp: In function ‘void caffe::caffe_cpu_sign(int, const Dtype*, Dtype*)’:
./include/caffe/util/math_functions.hpp:160:42: error: ‘caffe_sign’ was not declared in this scope
 DEFINE_CAFFE_CPU_UNARY_FUNC(sign, y[i] = caffe_sign<Dtype>(x[i]));
                                          ^
./include/caffe/util/math_functions.hpp:155:7: note: in definition of macro ‘DEFINE_CAFFE_CPU_UNARY_FUNC’
       operation; \
       ^
./include/caffe/util/math_functions.hpp:160:58: error: expected primary-expression before ‘>’ token
 DEFINE_CAFFE_CPU_UNARY_FUNC(sign, y[i] = caffe_sign<Dtype>(x[i]));
                                                          ^
./include/caffe/util/math_functions.hpp:155:7: note: in definition of macro ‘DEFINE_CAFFE_CPU_UNARY_FUNC’
       operation; \
       ^
Makefile:572: recipe for target '.build_release/src/caffe/layers/absval_layer.o' failed
make: *** [.build_release/src/caffe/layers/absval_layer.o] Error 1

My OS is ubuntu 16.04.

**Comment by orsharir** [comment]
I need more information on your system. What GPU are you using? and have you installed all the prerequisites listed here: http://caffe.berkeleyvision.org/installation.html#prerequisites ?

**Comment by JaeLee18** [comment]
Yes, I have installed all the prerequisites and I could compile everything from Caffe master git branch. But the problem was occurred in ~/TMM/deps/simnets
I am using Mid 2015 MacBook Pro with CPU-ONLY.
Also, I am trying to run the program using Parallels.

**Comment by orsharir** [comment]
Due to a minor bug, you'll need to compile without the CPU-ONLY flag. You'll still be able to run it on the CPU (by setting the solver_mode flag to CPU), though I'd warn you that the CPU code is not highly optimize -- predicting should be fine, but training will likely take too much time to be of any practical use.

Also, you don't really need to use parallels, as I've developed most of the code on my Macbook Pro (mid 2012).

**Comment by JaeLee18** [comment]
Thank you.
I compiled without error!
