### ISSUE TITLE
ght_model, train plan not valid

### ISSUE THREAD

**Issue by JaeLee18** [HUJI-Deep/TMM#2]
Hello,

After I compiled caffe,

I tried to run "run.py" in/TMM/exp/mnist/ghp_model/train

I got this:

**All required datasets are present.
Generating pre-trained model:

All required datasets are present.
Invalid train plan!

Try `python hyper_train.py --help` for more information
Error calling hyper_train script
=============== DONE ===============
Invalid train plan!

Try `python hyper_train.py --help` for more information
Error calling hyper_train script**

I looked up "hyper_train.py" but I am not sure how to fix this error.

**Comment by orsharir** [comment]
This is odd... I'll need to know the exact reason that it happens. Please add at the beginning of hyper_train.py the following line:
```
import traceback
```
And add after line 320:
```
traceback.print_exc()
```
and reply with the output of executing "run.py".

**Comment by orsharir** [comment]
Also, are you using python 2.7?

**Comment by JaeLee18** [comment]
Hello,

I am using **python2.7.10.**

After I put traceback.print_exc()

I found that I do not have module jinja2

after I do pip install jinja2,

I am getting this:
_➜  train git:(master) ✗ python run.py 
All required datasets are present.
Generating pre-trained model:

All required datasets are present.
None
=============== DONE ===============
None
Cannot find weights file. Skipped run!_

I got "ght_model_train.csv" but the file is empty because I got this error.
Traceback (most recent call last):
  File "/TMM/deps/simnets/tools/extra/hyper_train.py", line 368, in execute
    indices = list(indices)
TypeError: 'int' object is not iterable

**Comment by orsharir** [comment]
First, be sure you run the following command inside deps/simnets/python:
```
pip install -r requirements.txt
```
This is to make sure you have all required python packages.

Next, you'll have to delete the previously generated files (ght_model_train*), inside both the train and the train/init directory as well. Then, try and run the scripts again.

**Comment by JaeLee18** [comment]
I completely  removed TMM folder and re-cloned the repository.
After I did "make all -j8" and I ran the "run.py" in the train folder.

This is my command history:
git clone --recursive https://github.com/HUJI-Deep/TMM.git         
make all -j8 (in deps/simnets with my config file)
make pycaffe -j8
cd TMM/exp/mnist/ght_model/train
python run.py 

then I have this result

Generating databases
#######
Downloading train-images-idx3-ubyte.gz
[==================================================] 6361.0 KBps
Done
#######
Downloading train-labels-idx1-ubyte.gz
[==================================================] 1082.0 KBps
Done
#######
Downloading t10k-images-idx3-ubyte.gz
[==================================================] 5853.0 KBps
Done
#######
Downloading t10k-labels-idx1-ubyte.gz
[==================================================] 144.0 KBps
Done
#######
Unarchiving: train-images-idx3-ubyte.gz
Unarchiving: train-labels-idx1-ubyte.gz
Unarchiving: t10k-images-idx3-ubyte.gz
Unarchiving: t10k-labels-idx1-ubyte.gz
#######
Writing the whole train data...
#######
Writing partial train data for cross-validation...
#######
Writing validation data...
#######
Writing test data...
#######
Done!
Generating pre-trained model:

All required datasets are present.
===================
i: 1 | run_idx_1: 1 | sim1_num_instances: 32

 
Previous run has stopped unexpectedly. Continue? [y/n] y
 
=============== DONE ===============
Cannot find weights file. Skipped run!




I am not sure why I got this"Previous run has stopped unexpectedly. Continue?" even, I deleted whole TMM folder and re-cloned the TMM.


https://goo.gl/GJk668

this is the TMM.zip for your information.

**Comment by orsharir** [comment]
You should look at the generate log files that show the reason for failing. In this case the error message is regarding failing to "connect" to the GPU. You've previously wrote you don't have a GPU on your system. In this case you should modify the net.prototmp file (both in train directory and in init) and change the "solver_mode" flag to CPU from GPU. However, I warn you that it will most likely be too slow to be of any use. Our CPU code is quite simplistic and not optimized.
