### ISSUE TITLE
No directory: exp/mnist/lenet

### ISSUE THREAD

**Issue by JaeLee18** [HUJI-Deep/TMM#3]
Hello,

I am trying to do 
https://github.com/HUJI-Deep/Generative-ConvACs/tree/master/exp/mnist/dpm

But in the git repository, I do not have "exp/mnist/lenet/train/run.py".
Did "lenet" rename for something else?

Is there any alternative way to redo the experiment?

I am using Ubuntu 16.04 and GTX 1070.

Thank you.

**Comment by orsharir** [comment]
Hey,

That missing model is simply the baseline lenet model that is bundled with Caffe. Somehow we've forgot to include it in this repo as well. We'll update the repo with that missing script, and update here afterwards.

Sorry about the issue,
Or.

**Comment by ronentk** [comment]
Hi, 
I've added the LeNet experiment here:
https://github.com/HUJI-Deep/Generative-ConvACs/tree/master/exp/mnist/lenet/train

Let us know if you have other questions,
Ronen

**Comment by JaeLee18** [comment]
Thank you.
I successfully got the result.
